# Generated by Django 3.1.7 on 2021-06-15 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientReg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Patient_Name', models.CharField(max_length=20)),
                ('Patient_Age', models.PositiveIntegerField()),
                ('Patient_Bloodgroup', models.CharField(max_length=20)),
                ('Patient_Item', models.CharField(max_length=20)),
                ('Patient_Phno', models.IntegerField()),
                ('Patient_Address', models.TextField()),
                ('Patient_HealthCertificate', models.ImageField(upload_to='Donor_HealthCertificate')),
            ],
        ),
    ]
