# Generated by Django 3.1.7 on 2021-06-16 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_patientreg'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Patient_Name', models.CharField(max_length=20)),
                ('Patient_Age', models.PositiveIntegerField()),
                ('Patient_NeedItem', models.CharField(max_length=20)),
                ('Patient_Phno', models.IntegerField()),
                ('Patient_Address', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='donorreg',
            name='Donor_Bloodgroup',
        ),
        migrations.RemoveField(
            model_name='patientreg',
            name='Patient_Bloodgroup',
        ),
    ]
