# Generated by Django 3.1.7 on 2021-06-16 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210616_0806'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hopitals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hospital_Name', models.CharField(max_length=30)),
                ('Hospital_Loc', models.CharField(max_length=30)),
                ('Avaliable_Organs', models.CharField(max_length=30)),
                ('Contact', models.IntegerField()),
            ],
        ),
    ]
