# Generated by Django 3.1.7 on 2021-06-19 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_hopitals'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PatientRequest',
        ),
    ]
